### ISSUE TITLE
error in statement if (seg$clonal == "no") 

### ISSUE THREAD

**Issue by sahliatef** [Wedge-lab/battenberg#120]
https://github.com/Wedge-lab/battenberg/blob/1796d9da6e98353c6995b2f73db72812b80a4986/R/fitcopynumber.R#L1124-L1130

For few samples the execution is stopped and we get the folowing error message

Error in if (seg$clonal == "no") { : 
  missing value where TRUE/FALSE needed
Calls: callChrXsubclones
Execution halted

We thought it would be fixed if we replace the statement in line 1095 "if (nrow(BBloh)>0)" by "if (nrow(BBloh)>1)"
But this did not fix the issue and I get the following error message

Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
Calls: callChrXsubclones -> rbind -> rbind
Execution halted

**Comment by nansari-pour** [comment]
The error seems to be due to seg$clonal being NA (simply neither "yes" nor "no"). There has to be something odd in one of the rows of the PCF dataframe. Could you please share the PCF dataframe of one of those few samples - it is not clear to me at what stage things are going wrong in these rare cases.

**Comment by nansari-pour** [comment]
The error seems to be due to seg$clonal being NA (simply neither "yes" nor "no") probably due to sd calculation. This is identical to issue #77 so I'll close this and deal with it there as it also provides examples of PCF and BBloh.
