### ISSUE TITLE
chr names bug

### ISSUE THREAD

**Issue by gevro** [Wedge-lab/battenberg#66]
https://github.com/Wedge-lab/battenberg/blob/82553a971646f55544080791b53ee4e4eb4f5767/R/prepare_wgs.R#L54-L56

Hi, 
Note these 'gsub' lines in 2.2.10 are causing a bug in running hg38 with "chr" prefix contigs. These lines are removing "chr" and causing the subsequent line in gc.correct.wgs to fail to match up entries between Tumor_LogR and GC_data.

locimatches = match(x = paste0(Tumor_LogR$Chromosome, "_", 
        Tumor_LogR$Position), table = paste0(GC_data$chr, "_", 
        GC_data$Position))

**Comment by jcesar101** [comment]
Hi,

apologies for replying until now. If this issue is still happening, could you please try using the last available version in the DEV branch from our repository? And also, there is a new set of reference files in [ORA](https://ora.ox.ac.uk/objects/uuid:08e24957-7e76-438a-bd38-66c48008cf52) with and without the 'chr' prefix in the chromosome names.
