### ISSUE TITLE
Bug in chr names in parse.imputeinfofile

### ISSUE THREAD

**Issue by gevro** [Wedge-lab/battenberg#67]
Hi,
There is a bug in the below lines causing hg38 (contigs with chr prefix) to fail.

https://github.com/Wedge-lab/battenberg/blob/604a5d240e80a7fd457fd2999002f93388de8345/R/impute.R#L68-L71

Specifically, this line: chr_names = unique(impute.info$chrom)
makes a list of unique chromosomes names and stores it in chr_names.

But this line accesses chr_names[chrom] using the chromosome name, but chr_names is not a named vector.
For example:
```
> chr_names
 [1] "chr1"  "chr2"  "chr3"  "chr4"  "chr5"  "chr6"  "chr7"  "chr8"  "chr9" 
[10] "chr10" "chr11" "chr12" "chr13" "chr14" "chr15" "chr16" "chr17" "chr18"
[19] "chr19" "chr20" "chr21" "chr22" "chrX" 
> chrom
[1] "chr10"
> chr_names[chrom]
[1] NA
```

Is there a version of Battenberg that can handle the "chr" prefixed contig names, specifically for hg38?

Thanks.

**Comment by jcesar101** [comment]
Hi,

similarly to issue #66, if this issue is still happening, could you please try using the last available version in the DEV branch from our repository? Could you please use the new set of reference files for hg38 available at [ORA](https://ora.ox.ac.uk/objects/uuid:08e24957-7e76-438a-bd38-66c48008cf52) that include or not the 'chr' prefix for the chromosome names?

**Comment by ssrinivasan2** [comment]
Hi, 

I am having the same issue - I tried with the latest version of the package (2.2.10) and re-downloaded the hg38 reference sets from ORA this morning, but the issue persists. 

Thanks so much!
