### ISSUE TITLE
Handling of chrX

### ISSUE THREAD

**Issue by seedgeorge** [Wedge-lab/battenberg#85]
Hi, 
I've successfully run battenberg on some deep WGS samples and the results look good - I'm wondering if there are plans to handle chromosome X in male samples more comprehensively? It would be nice to look at certain amplifications...
Thanks!

**Comment by acirrincio** [comment]
were you able to use the docker successfully from this github page?

**Comment by tobyaicher** [comment]
Hi,

I wanted to follow-up on this question: When I run battenberg on a male it only outputs the two PAR regions of the X chromosome. However, I noticed there is a callChrXsubclones function. Is it possible to enable this function in Battenberg? It seems like the issue is that to run this function it requires X to be in the chr.names paramter, but the function that generates the chr.names paramter (get.chr.names and parse.inputinfofile) discard all the chromosomes that are not PAR=1 in the imput.info file. 

I feel like an easy fix would be just to add chrX to the get.chr.names parameter, thereby allowing the callChrxsubclones function to run. Unless I am missing an update that allows callChrdxsubclones to run but it seems when I run Battenberg I don't get chrosome X copy number information outside of the PAR regions.

Thank you
